CREATE DATABASE newsweek;

\C newsweek;
CREATE TABLE IF NOT EXISTS department(
 id SERIAL PRIMARY KEY,
 name VARCHAR
);
CREATE TABLE IF NOT EXISTS USERS(
 id SERIAL PRIMARY KEY,
 name VARCHAR,
 email VARCHAR,
 badge VARCHAR
);
CREATE TABLE IF NOT EXISTS news(
 id SERIAL PRIMARY KEY,
 news VARCHAR,
 department VARCHAR
 )